name: Changesets

on:
  push:
    branches:
      - main

permissions:
  contents: write
  pull-requests: write

jobs:
  changesets:
    runs-on: ubuntu-latest
    outputs:
      published: ${{ steps.changesets.outputs.hasChangesets == 'false' }}
    steps:
      - name: Setup | Checkout
        uses: actions/checkout@v4

      - name: Setup | GitHub App
        id: token
        uses: tibdex/github-app-token@v2
        with:
          app_id: ${{ secrets.APP_ID }}
          private_key: ${{ secrets.APP_PRIVATE_KEY }}

      - name: Setup | Node.js
        uses: shun-shobon/actions/setup-node@master
        with:
          node-version-file: .tool-versions

      - name: Run | Build
        run: pnpm run build

      - name: Run | Changesets
        uses: changesets/action@v1
        id: changesets
        env:
          GITHUB_TOKEN: ${{ steps.token.outputs.token }}

  release:
    needs: changesets
    if: ${{ needs.changesets.outputs.published == 'true' }}
    permissions:
      contents: read
      packages: write
    uses: ./.github/workflows/release.yml
    secrets: inherit
