name: lint
on:
  push:

permissions:
  contents: read

jobs:
  lint:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        package:
          - base
          - react
          - utils
    steps:
      - uses: actions/checkout@v3
      - uses: shun-shobon/actions/setup-node@master
        with:
          node-version: lts/*

      - run: pnpm build
      - run: pnpm run --filter ./packages/${{ matrix.package }} lint:eslint
      - run: pnpm run --filter ./packages/${{ matrix.package }} lint:tsc
