name: Release please

on:
  push:
    branches:
      - master

jobs:
  release-please:
    runs-on: ubuntu-latest
    outputs:
      releases_created: ${{ steps.release.outputs.releases_created }}
    steps:
      - name: Setup | GitHub App
        id: token
        uses: tibdex/github-app-token@v2
        with:
          app_id: ${{ secrets.APP_ID }}
          private_key: ${{ secrets.APP_PRIVATE_KEY }}

      - name: Run | Release please
        uses: google-github-actions/release-please-action@v3
        id: release
        with:
          token: ${{ steps.token.outputs.token }}
          release-type: node
          command: manifest
          config-file: .github/release-please-config.json
          manifest-file: .github/.release-please-manifest.json

  release:
    needs: release-please
    if: ${{ needs.release-please.outputs.releases_created }}
    permissions:
      contents: read
      packages: write
    uses: ./.github/workflows/release.yml
    secrets: inherit
