name: release-please

on:
  push:
    branches:
      - master

permissions:
  contents: write
  packages: write

jobs:
  release-please:
    runs-on: ubuntu-latest
    outputs:
      releases_created: ${{ steps.release.outputs.releases_created }}
    steps:
      - uses: actions/checkout@v3

      - id: token
        uses: tibdex/github-app-token@v1
        with:
          app_id: ${{ secrets.APP_ID }}
          private_key: ${{ secrets.APP_PRIVATE_KEY }}

      - uses: google-github-actions/release-please-action@v3
        id: release
        with:
          token: ${{ steps.token.outputs.token }}
          release-type: node
          command: manifest

  release:
    needs: release-please
    if: ${{ needs.release-please.outputs.releases_created }}
    uses: ./.github/workflows/release.yml
    secrets: inherit
