name: release-please

on:
  push:
    branches:
      - master

permissions:
  contents: read
  packages: write

jobs:
  release-please:
    runs-on: ubuntu-latest
    outputs:
      releases_created: ${{ steps.release.outputs.releases_created }}
    steps:
      - uses: actions/checkout@v3

      - uses: google-github-actions/release-please-action@v3
        id: release
        with:
          token: ${{ secrets.RELEASE_TOKEN }}
          release-type: node
          command: manifest

  release:
    needs: release-please
    if: ${{ needs.release-please.outputs.releases_created }}
    uses: ./.github/workflows/release.yml
    secrets: inherit
