name: Release
on:
  workflow_call:
    secrets:
      NPM_TOKEN:
        required: true
  workflow_dispatch:

permissions:
  contents: read
  packages: write

jobs:
  release:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        include:
          - name: npm
            url: https://registry.npmjs.org/
          - name: GitHub Packages
            url: https://npm.pkg.github.com/
    steps:
      - name: Setup | Checkout
        uses: actions/checkout@v4

      - name: Setup | Node.js
        uses: shun-shobon/actions/setup-node@master
        with:
          node-version-file: .tool-versions

      - name: Setup | Registry
        uses: actions/setup-node@v4
        with:
          registry-url: ${{ matrix.url }}

      - name: Run | Build
        run: pnpm build

      - name: Publish | ${{ matrix.name }}
        run: pnpm publish -r --access public
        env:
          NODE_AUTH_TOKEN: ${{ matrix.name == 'npm' && secrets.NPM_TOKEN || secrets.GITHUB_TOKEN }}
